name: Docker Build Trips

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:

  publish:
    name: Docker Build Trips

    runs-on: ubuntu-latest

    steps:      
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: chixcancode-projects/openhack-devops-team/trips
        username: ${{ github.actor }}
        password: ${{ secrets.githubtoken }}
        registry: docker.pkg.github.com
        workdir: ./apis/trips

  deploy:
    needs: [publish]
    name: Trips App Service Deploy
    
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Login via Docker to GH'
        uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.githubtoken }}
