name: Docker Build User Java

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:

  publish:
    name: Docker Build User Java

    runs-on: ubuntu-latest

    steps:      
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: chixcancode-projects/openhack-devops-team/user-java
        username: ${{ github.actor }}
        password: ${{ secrets.githubtoken }}
        registry: docker.pkg.github.com
        tags: "latest, ${{ github.run_number }}"
        workdir: ./apis/user-java

  deploy:
    needs: [publish]
    name: UserJava App Service Deploy
    
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Login via Docker to GH'
        uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.githubtoken }}
    
      - name: 'Push to Azure App Service'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'openhack4t18p479userjava'
          images: ${{ env.CONTAINER_REGISTRY }}/chixcancode-projects/openhack-devops-team/user-java:latest
          slot-name: 'staging'
